blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://craftcms.com/docs
    about: Read the official documentation
  - name: Knowledge Base
    url: https://craftcms.com/knowledge-base
    about: Find answers to common problems
  - name: "Feature Request: Craft CMS"
    url: https://github.com/craftcms/cms/discussions/new?category=ideas
  - name: "Feature Request: Craft Console / Plugin Store"
    url: https://github.com/craftcms/console/discussions/new?category=ideas
  - name: "Feature Request: Craft Cloud"
    url: https://github.com/craftcms/cloud/discussions/new?category=ideas
  - name: "Feature Request: Craft Commerce"
    url: https://github.com/craftcms/commerce/discussions/new?category=ideas
  - name: "Bug Report: Craft CMS"
    url: https://github.com/craftcms/cms/issues/new/choose
  - name: "Bug Report: Craft Console / Plugin Store"
    url: https://github.com/craftcms/console/issues/new/choose
  - name: "Bug Report: Craft Cloud"
    url: https://craftcms.com/contact
  - name: "Bug Report: Craft Commerce"
    url: https://github.com/craftcms/commerce/issues/new/choose
  - name: Developer Support Services
    url: https://craftcms.com/support-services
    about: Priority developer support from the team that makes Craft
  - name: Craft Discord
    url: https://craftcms.com/discord
    about: Meet the community
  - name: Stack Exchange
    url: http://craftcms.stackexchange.com/
    about: Get help and help others
