name: Plugins

on:
  workflow_call:
    secrets:
      token:
        required: false
      slack_webhook_url:
        required: false
    inputs:
      craft_version:
        default: '3'
        type: string
      php_version:
        default: '8.0'
        type: string
      jobs:
        default: '["ecs"]'
        type: string
      notify_slack:
        default: false
        type: boolean
      slack_subteam:
        default: ''
        type: string
concurrency:
  group: ci-global-${{ github.ref }}
  cancel-in-progress: true
jobs:
  code-quality:
    name: Code Quality
    if: ${{ contains(fromJSON(inputs.jobs), 'ecs') || contains(fromJSON(inputs.jobs), 'phpstan') || contains(fromJSON(inputs.jobs), 'prettier') }}
    uses: ./.github/workflows/code-quality.yml
    with:
      php_version: ${{ fromJSON('{"3":"7.2","4":"8.0"}')[inputs.craft_version] || inputs.php_version }}
      jobs: ${{ inputs.jobs }}
  tests:
    name: Tests
    needs: [code-quality]
    if: ${{ contains(fromJSON(inputs.jobs), 'tests') }}
    uses: ./.github/workflows/codecept.yml
    with:
      php_versions: ${{ toJSON(fromJSON('{"3":["7.2", "7.3", "7.4", "8.0", "8.1"],"4":["8.0", "8.1"]}')[inputs.craft_version]) }}
  notify-slack:
    name: Notify Slack
    needs: [code-quality, tests]
    if: ${{ always() && inputs.slack_subteam && inputs.notify_slack }}
    uses: ./.github/workflows/notify-slack.yml
    with:
      success: ${{ !contains(needs.*.result, 'failure') }}
      failure: ${{ contains(needs.*.result, 'failure') }}
      failure_text_prefix: ${{ inputs.slack_subteam }}
    secrets: inherit