name: Code Quality

on:
  workflow_call:
    inputs:
      craft_version:
        default: '3'
        type: string
      php_version:
        default: '8.0'
        type: string
      node_version:
        default: '16'
        type: string
      working_directory:
        default: '.'
        type: string
      jobs:
        default: '["ecs"]'
        type: string
jobs:
  ecs:
    name: ECS
    if: ${{ contains(fromJSON(inputs.jobs), 'ecs') }}
    uses: ./.github/workflows/ecs.yml
    with:
      craft_version: ${{ inputs.craft_version }}
      php_version: ${{ inputs.php_version }}
      working_directory: ${{ inputs.working_directory }}
    secrets: inherit
  phpstan:
    name: PHPStan
    if: ${{ contains(fromJSON(inputs.jobs), 'phpstan') }}
    uses: ./.github/workflows/phpstan.yml
    with:
      craft_version: ${{ inputs.craft_version }}
      php_version: ${{ inputs.php_version }}
      working_directory: ${{ inputs.working_directory }}
    secrets: inherit
  prettier:
    name: Prettier
    if: ${{ contains(fromJSON(inputs.jobs), 'prettier') }}
    uses: ./.github/workflows/prettier.yml
    with:
      node_version: ${{ inputs.node_version }}
      working_directory: ${{ inputs.working_directory }}
  rector:
    name: Rector
    if: ${{ contains(fromJSON(inputs.jobs), 'rector') }}
    uses: ./.github/workflows/rector.yml
    with:
      craft_version: ${{ inputs.craft_version }}
    secrets: inherit
