name: Plugins

on:
  workflow_call:
    inputs:
      php_version:
        default: '8.0'
        type: string
      jobs:
        default: '["ecs"]'
        type: string
concurrency:
  group: ci-global-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ecs:
    name: ECS
    if: ${{ contains(fromJSON(inputs.jobs), 'ecs') }}
    uses: ./.github/workflows/ecs.yml
    with:
      php_version: ${{ inputs.php_version }}
  phpstan:
    name: PHPStan
    if: ${{ contains(fromJSON(inputs.jobs), 'phpstan') }}
    uses: ./.github/workflows/phpstan.yml
    with:
      php_version: ${{ inputs.php_version }}
  prettier:
    name: Prettier
    if: ${{ contains(fromJSON(inputs.jobs), 'prettier') }}
    uses: ./.github/workflows/prettier.yml
