name: ci
on:
  workflow_call:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}-1
  cancel-in-progress: true

jobs:

  ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-ansi --no-progress

      - name: Run ECS checks
        run: vendor/bin/ecs check --ansi

      - name: Cancel current workflow run
        if: ${{ failure() }}
        uses: actions/github-script@v4
        with:
          script: |
            github.actions.cancelWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.runId
            })