name: Notify Slack
on:
  workflow_call:
    inputs:
      success:
        required: true
        type: boolean
      success_text:
        type: string
        required: false
        description: Slack message when succeeded.
        default: '<${{ github.repositoryUrl }}|${{ github.repository }}> build completed successfully for `${{ github.ref_name }}` by @${{ github.actor }}'
      failure_text:
        type: string
        required: false
        description: Slack message when failed.
        default: '<!subteam^{{ secrets.slack_group_id }}> <${{ github.repositoryUrl }}|${{ github.repository }}> build failed for `${{ github.ref_name }}` by @${{ github.actor }}'
      cancelled_text:
        type: string
        required: false
        description: Slack message when cancelled.
        default: '<${{ github.repositoryUrl }}|${{ github.repository }}> build was cancelled for `${{ github.ref_name }}` by @${{ github.actor }}'
    secrets:
      token:
        required: true
      slack_webhook_url:
        required: true
      slack_group_id:
        required: true
jobs:
  notify-on-success:
    name: Notify Slack on success
    runs-on: ubuntu-latest
    if: ${{ inputs.success }}
    steps:
      - name: Notify Slack
        uses: innocarpe/actions-slack@v1
        with:
          status: 'success'
          success_text: ${{ inputs.success_text }}
          failure_text: ${{ inputs.failure_text }}
          cancelled_text: ${{ inputs.cancelled_text }}
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
  notify-on-failure:
    name: Notify Slack on failure
    runs-on: ubuntu-latest
    if: ${{ ! inputs.success }}
    steps:
      - name: Notify Slack
        uses: innocarpe/actions-slack@v1
        with:
          status: 'failure'
          success_text: ${{ inputs.success_text }}
          failure_text: ${{ inputs.failure_text }}
          cancelled_text: ${{ inputs.cancelled_text }}
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
