name: PHPStan
on:
  workflow_call:
    inputs:
      php_version:
        required: true
        type: string
jobs:
  phpstan:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ inputs.php_version }}
          extensions: 'ctype,curl,dom,iconv,imagick,intl,json,mbstring,openssl,pcre,pdo,reflection,spl,zip'
          ini-values: post_max_size=256M, max_execution_time=180, memory_limit=512M
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Check .env.example.mysql exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "tests/.env.example.mysql"
      - name: Copy tests .env
        if: ${{ steps.check_files.outputs.files_exists == 'true' }}
        run: cp ./tests/.env.example.mysql ./tests/.env
      - name: Create folders
        if: ${{ steps.check_files.outputs.files_exists == 'true' }}
        run: mkdir tests/_craft/storage/runtime/compiled_classes
      - name: Build Codeception support files
        if: ${{ steps.check_files.outputs.files_exists == 'true' }}
        run: "vendor/bin/codecept build"
      - name: Run PHPStan checks
        run: "vendor/bin/phpstan --memory-limit=2G"
      - name: Cancel current workflow run on failure
        if: ${{ failure() }}
        uses: actions/github-script@v4
        with:
          script: |
            github.actions.cancelWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.runId
            })
