name: PHPStan
on:
  workflow_call:
    inputs:
      php_version:
        required: true
        type: string
runs:
  using: "composite"
  steps:
    - uses: ./.github/workflows/phpstan.yml
      with:
        php_version: ${{ inputs.php_version }}