name: Plugins

env:
  CRAFT_PHP_VERSIONS: '{"3": "7.2", "4": "8.0"}'

on:
  workflow_call:
    inputs:
      craft_version:
        required: true
        default: '3'
        type: string
      jobs:
        default: '["ecs"]'
        type: string
      notify_slack:
        default: true
        type: boolean
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ecs3:
    name: ECS
    if: ${{ contains(fromJSON(inputs.jobs), 'ecs') && inputs.craft_version == '3' }}
    uses: ./.github/workflows/ecs.yml
    with:
      php_version: '7.2'
  ecs4:
    name: ECS
    if: ${{ contains(fromJSON(inputs.jobs), 'ecs') && inputs.craft_version == '4' }}
    uses: ./.github/workflows/ecs.yml
    with:
      php_version: '8.0'