name: Plugins

env:
  CRAFT_PHP_VERSIONS: '{"3": "7.2", "4": "8.0"}'

on:
  workflow_call:
    inputs:
      craft_version:
        default: '3'
        type: string
      php_version:
        default: '8.0'
        type: string
      jobs:
        default: '["ecs"]'
        type: string
      notify_slack:
        default: true
        type: boolean
concurrency:
  group: ci-plugins-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ecs3:
    name: ECS
    if: ${{ contains(fromJSON(inputs.jobs), 'ecs') }}
    uses: ./.github/workflows/ecs.yml
    with:
      php_version: ${{ fromJSON('{"3":"7.2","4":"8.0"}')[inputs.craft_version] || inputs.php_version }}