name: Plugins

env:
  CRAFT_PHP_VERSIONS: '{"3": "7.2", "4": "8.0"}'

on:
  workflow_call:
    secrets:
      token:
        required: false
      slack_webhook_url:
        required: false
    inputs:
      craft_version:
        default: '3'
        type: string
      php_version:
        default: '8.0'
        type: string
      jobs:
        default: '["ecs"]'
        type: string
      notify_slack:
        default: true
        type: boolean
      slack_subteam:
        default: <!subteam^SGFL9NKNZ>
        type: string
concurrency:
  group: ci-plugins-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ecs:
    name: ECS
    if: ${{ contains(fromJSON(inputs.jobs), 'ecs') }}
    uses: ./.github/workflows/ecs.yml
    with:
      php_version: ${{ fromJSON('{"3":"7.2","4":"8.0"}')[inputs.craft_version] || inputs.php_version }}
  phpstan:
    name: PHPStan
    if: ${{ contains(fromJSON(inputs.jobs), 'phpstan') }}
    uses: ./.github/workflows/phpstan.yml
    with:
      php_version: ${{ fromJSON('{"3":"7.2","4":"8.0"}')[inputs.craft_version] || inputs.php_version }}
  prettier:
    name: Prettier
    if: ${{ contains(fromJSON(inputs.jobs), 'prettier') }}
    uses: ./.github/workflows/prettier.yml
  notify-slack:
    name: Notify Slack
    needs: [ecs, phpstan, prettier]
    if: ${{ always() && inputs.slack_subteam && inputs.notify_slack }}
    uses: ./.github/workflows/notify-slack.yml
    with:
      success: ${{ !contains(needs.*.result, 'failure') }}
      failure: ${{ contains(needs.*.result, 'failure') }}
      failure_text_prefix: ${{ inputs.slack_subteam }}
    secrets: inherit