name: Prettier
on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string

jobs:
  prettier:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install node deps
        run: npm ci

      - name: Run Prettier checks
        run: npx prettier --check .
