name: Prettier
on:
  workflow_call:
jobs:
  prettier:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if .nvmrc exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".nvmrc"

      - name: Setup node nvmrc
        if: ${{ steps.check_files.outputs.files_exists == 'true' }}
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Setup node explicit
        if: ${{ steps.check_files.outputs.files_exists == 'false' }}
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install node deps
        run: npm ci

      - name: Run Prettier checks
        run: npx prettier --check .
