name: Prettier
env:
  CRAFT_FONTAWESOME_TOKEN: ${{ secrets.CRAFT_FONTAWESOME_TOKEN }}

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      working_directory:
        default: '.'
        type: string
jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install node deps
        run: npm ci

      - name: Run Prettier checks
        run: npx prettier --check .
